### ISSUE TITLE
Cannot get the SPI part to work

### ISSUE THREAD

**Issue by vladkorotnev** [t-mat/esp32-vga-experiment#8]
I am trying to reuse the SPI part of this project to drive a set of LED matrices dynamically. For that I copied the `myspi_*` setup methods as well as part of the `kickPeripherals` method to perform the SPI initialization in QIO mode like so:

https://github.com/vladkorotnev/plasma-clock/blob/hw-spi/src/display/akizuki_k875.cpp#L149-L342

(I removed the `spicommon_*` calls because it seems they do not exist anymore)

However, I don't see any activity on the SPI bus after executing the code. Even reverting back to original code and removing the `spi_bus_initialize` call, there is still nothing happening. 

Am  I missing some extra step needed to start the SPI peripheral? Are those low level registers and the bringup procedure even documented anywhere?

Thanks

**Comment by t-mat** [comment]
Hi,

Since I don't use ESP32 / ESP-IDF for a while, the following responses may not be correct.

(I personally think [esp-idf](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/spi_master/lcd/main/spi_master_example_main.c) is a good option nowadays though)



> I don't see any activity on the SPI bus after executing the code.

If you mean all SPI output pins (MOSI, CLK and CS) don't respond completely, it means SPI DMA did not start. Therefore, it means your software and/or hardware setup is wrong.

If CS and CLK are active (CS == low and CLK is ticking), it may mean something in your initialization is wrong especially 
 SPI mode slection, DMA linked list, SPI clock selection, etc.

If you didn't check these pins, I recommend you to check them directly with oscilloscope and/or logic analyzer.
(LED may be enough for low frequency clock for testing purpose)


> Am I missing some extra step needed to start the SPI peripheral?

I don't know anything about your code, but basically `SPI_CMD_REG.SPI_USR = 1;` is enough to start them.

See also the decription at "ESP32 Technical Reference Manual Version 5.2", 7.8 Registers, Register 7.1. SPI_CMD_REG

You can also observe them via the following readonly status registers:

- SPI_DMA_STATUS_REG
- SPI_DMA_INT_ST_REG
- SPI_DMA_TSTATUS_REG

> Are those low level registers and the bringup procedure even documented anywhere?

As you know, the [ESP32 technical reference manual](https://www.espressif.com/en/support/documents/technical-documents?keys=esp32+technical+reference+manual) has a dedicated section for DMA (chapter 6) and SPI (chapter 7).

Also "Reset and Clock" (chapter 3) may help you to determine the actual clock source and its frequency.

**Comment by vladkorotnev** [comment]
Thanks so much for the detailed answer!

The ESP-IDF sadly still doesn't allow circular looped transactions, so that's why I had to refer to your code. And I'm trying to drive some ancient LED panels (Akizuki Denshi K875) which are just basically crossed shift registers, so it is very timing critical sadly, otherwise the segment brightness becomes uneven.

However, I've changed it to basically initializing SPI with the IDF driver, doing a single empty transaction, and then customizing the registers directly — that seems to have worked for the most part! 

Now I just need to make it somehow bring CS back to high after sending every entry in the linked list, and that should probably work fine.

**Comment by vladkorotnev** [comment]
In the end I solved the CS problem by using a somewhat cursed mix of inserting bits for the LATCH signal into the data array, and using the GPIO pinmux + Motor Control peripherals as a makeshift tiny FPGA: https://github.com/vladkorotnev/plasma-clock/blob/hw-spi/src/display/akizuki_k875.cpp#L241-L328

Thanks once again for your help!

**Comment by t-mat** [comment]
Hi, I've skimmed through your project and code.
Thanks for your detailed comments, I understand the neat hack of MCPWM fault hanlder :)
Hope I also utilize these functionalities when I'll back to ESP32 coding.

**Comment by vladkorotnev** [comment]
Thanks so much, hope it indeed comes in handy. If anything I've also posted a walkthrough through all the solutions I've tried on Elchika, and tried to reasonably explain why they didn't work: https://elchika.com/article/467d0576-bf24-4973-b537-5be7c0d9504a/
